version: "2"
checks:
  method-count:
    enabled: false
    config:
      threshold: 20
  similar-code:
    enabled: false
    config:
      threshold: #language-specific defaults. overrides affect all languages.

## Excluding some folders from analysis
exclude_patterns:
- "src/DataFixtures/"
- "tests/"